set_property SRC_FILE_INFO {cfile:C:/Users/dries/ultrasoon/ultrasoon.srcs/constrs_1/new/constraint_ultrasoon.xdc rfile:../../../ultrasoon.srcs/constrs_1/new/constraint_ultrasoon.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports sonar_trig_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y19 [get_ports sonar_echo_0]
